In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split


In [2]:
date = {
    "Alina": [60, 165, True],
    "Bogdan": [72, 183, False],
    "Ciprian": [69, 178, False],
    "Diana": [55, 152, True],
    "Elena": [58, 168, True],
    "Andrei": [80, 185, False],
    "Mihai": [75, 177, False],
    "Irina": [62, 170, True],
    "Florin": [90, 190, False],
    "Maria": [53, 160, True],
    "Vlad": [70, 175, False],
    "Ioana": [50, 155, True],
    "Radu": [68, 172, False],
    "Ana": [59, 162, True],
    "George": [85, 182, False],
    "Larisa": [61, 167, True],
    "Stefan": [78, 180, False],
    "Bianca": [56, 158, True],
    "Paul": [74, 176, False],
    "Oana": [54, 163, True],
    "Cosmin": [82, 188, False],
    "Teodora": [57, 159, True],
    "Ionut": [76, 181, False],
    "Gabriela": [60, 164, True]
}

In [3]:
df = pd.DataFrame(date.values(), columns=["kg", "cm", "voce"])
df

kg   cm   voce
0   60  165   True
1   72  183  False
2   69  178  False
3   55  152   True
4   58  168   True
5   80  185  False
6   75  177  False
7   62  170   True
8   90  190  False
9   53  160   True
10  70  175  False
11  50  155   True
12  68  172  False
13  59  162   True
14  85  182  False
15  61  167   True
16  78  180  False
17  56  158   True
18  74  176  False
19  54  163   True
20  82  188  False
21  57  159   True
22  76  181  False
23  60  164   True

In [4]:
df["Gen"] = df["voce"].apply(lambda x: 1 if x else 0)
df


kg   cm   voce  Gen
0   60  165   True    1
1   72  183  False    0
2   69  178  False    0
3   55  152   True    1
4   58  168   True    1
5   80  185  False    0
6   75  177  False    0
7   62  170   True    1
8   90  190  False    0
9   53  160   True    1
10  70  175  False    0
11  50  155   True    1
12  68  172  False    0
13  59  162   True    1
14  85  182  False    0
15  61  167   True    1
16  78  180  False    0
17  56  158   True    1
18  74  176  False    0
19  54  163   True    1
20  82  188  False    0
21  57  159   True    1
22  76  181  False    0
23  60  164   True    1

In [5]:
df["voce"] = df["voce"].apply(lambda x: int(x))
df


kg   cm  voce  Gen
0   60  165     1    1
1   72  183     0    0
2   69  178     0    0
3   55  152     1    1
4   58  168     1    1
5   80  185     0    0
6   75  177     0    0
7   62  170     1    1
8   90  190     0    0
9   53  160     1    1
10  70  175     0    0
11  50  155     1    1
12  68  172     0    0
13  59  162     1    1
14  85  182     0    0
15  61  167     1    1
16  78  180     0    0
17  56  158     1    1
18  74  176     0    0
19  54  163     1    1
20  82  188     0    0
21  57  159     1    1
22  76  181     0    0
23  60  164     1    1

In [6]:
x = df[["kg", "cm", "voce"]]
y = df["Gen"]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((19, 3), (5, 3), (19,), (5,))

In [9]:
tf.random.set_seed(42)

model_1 = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(3,)),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

model_1.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"]
)

history_1 = model_1.fit(x_train, y_train, epochs=100, verbose=0)

In [10]:
model_1.evaluate(x_test, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - accuracy: 1.0000 - loss: 0.1410


[0.1409735083580017, 1.0]

In [11]:
y_prezis = model_1.predict(x_test)
y_prezis

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[0.01782945],
       [0.10181186],
       [0.7314827 ],
       [0.16907418],
       [0.9216359 ]], dtype=float32)

In [12]:
pd.DataFrame({"y_test": y_test, "y_prezis": y_prezis.flatten()})

y_test  y_prezis
8        0  0.017829
16       0  0.101812
0        1  0.731483
18       0  0.169074
11       1  0.921636

In [13]:
y_test

8     0
16    0
0     1
18    0
11    1
Name: Gen, dtype: int64

In [14]:
y_prezis

array([[0.01782945],
       [0.10181186],
       [0.7314827 ],
       [0.16907418],
       [0.9216359 ]], dtype=float32)

In [16]:
model_1.predict(np.array([[902, 182, 1]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step


array([[1.9967238e-18]], dtype=float32)

# Crearea unui model mai mic ("scurtare")

In [19]:
tf.random.set_seed(42)

model_2 = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(3,)),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(8, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

model_2.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"]
)

history_2 = model_2.fit(x_train, y_train, epochs=100, verbose=0)


In [20]:
y_prezis = model_2.predict(x_test)
y_prezis
pd.DataFrame({"y_test": y_test, "y_prezis": y_prezis.flatten()})

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


y_test  y_prezis
8        0  0.296183
16       0  0.372058
0        1  0.584922
18       0  0.396817
11       1  0.646720

In [21]:
tf.random.set_seed(42)

model_3 = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(3,)),
        tf.keras.layers.Dense(8, activation="relu"),
        tf.keras.layers.Dense(4, activation="relu"),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

model_3.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(),
    metrics=["accuracy"]
)

history_3 = model_3.fit(x_train, y_train, epochs=500, verbose=0)

In [22]:
y_prezis = model_3.predict(x_test)
y_prezis
pd.DataFrame({"y_test": y_test, "y_prezis": y_prezis.flatten()})

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step


y_test  y_prezis
8        0  0.447947
16       0  0.447947
0        1  0.695817
18       0  0.448461
11       1  0.781739