# pip install numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.4'

In [3]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

## ARRAY vs LISTA
array - homogen, lista - heterogena

In [5]:
o_lista = [101, 202, 303, 404]
print(o_lista, type(o_lista))

un_array  = np.array(o_lista)
print(un_array, type(un_array))

[101, 202, 303, 404] <class 'list'>
[101 202 303 404] <class 'numpy.ndarray'>


In [7]:
o_lista = [101, 202, 303, 404.4444]
print(o_lista, type(o_lista))

un_array  = np.array(o_lista)
print(un_array, type(un_array), un_array.dtype)

[101, 202, 303, 404.4444] <class 'list'>
[101.     202.     303.     404.4444] <class 'numpy.ndarray'> float64


In [8]:
o_lista = [101, 202, 303, 404.4444, "string"]
print(o_lista, type(o_lista))

un_array  = np.array(o_lista)
print(un_array, type(un_array), un_array.dtype)

[101, 202, 303, 404.4444, 'string'] <class 'list'>
['101' '202' '303' '404.4444' 'string'] <class 'numpy.ndarray'> <U32


In [9]:
o_lista = [101, 202, 303, 404.4444, "string", [999, 888, 777]]
print(o_lista, type(o_lista))


[101, 202, 303, 404.4444, 'string', [999, 888, 777]] <class 'list'>


In [13]:
un_array  = np.array([ [101, 202, 606], [303, 404, 505]])
print(un_array, type(un_array), un_array.dtype)

[[101 202 606]
 [303 404 505]] <class 'numpy.ndarray'> int64


## Operatii pe np.array

In [14]:
arr = np.array([44, 55, 66, 77, 88])
arr

array([44, 55, 66, 77, 88])

In [15]:
arr + 2

array([46, 57, 68, 79, 90])

In [17]:
[44, 55, 66, 77, 88]  + [3]

[44, 55, 66, 77, 88, 3]

In [18]:
arr = np.array([44, 55, 66, 77, 88])
arr + arr

array([ 88, 110, 132, 154, 176])

In [21]:
np.array([44, 55, 66, 77, 88]) + np.array([1, 2, 3, 4, 5])

array([45, 57, 69, 81, 93])

In [22]:
arr = np.array([44, 55, 66, 77, 88])

arr  / 2 + 10


array([32. , 37.5, 43. , 48.5, 54. ])

In [26]:
o_lista = [44, 55, 66, 77, 88]  

lista_rezultat = []

for i in o_lista:
    lista_rezultat.append(i / 2 + 10)
lista_rezultat


[32.0, 37.5, 43.0, 48.5, 54.0]

## Generare de numere

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.array( range(10) )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array = np.arange(10)
print(array, type(array), array.dtype)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int64


In [30]:
array.shape

(10,)

In [31]:
array = np.arange(10).reshape((2, 5))
print(array, type(array), array.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]] <class 'numpy.ndarray'> int64


In [32]:
array = np.arange(10).reshape((5, 2))
print(array, type(array), array.dtype)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] <class 'numpy.ndarray'> int64


In [34]:
array = np.arange(9).reshape((3, 3))
print(array, type(array), array.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]] <class 'numpy.ndarray'> int64


In [35]:
np.random.randint(1, 10)

5

In [41]:
np.random.randint(1, 10)

4

In [42]:
np.random.randint(1, 10, 10)

array([4, 1, 6, 1, 1, 6, 9, 1, 1, 6])

In [43]:
np.random.randint(1, 10, 10)

array([7, 1, 9, 1, 1, 8, 9, 7, 9, 7])

In [45]:
np.random.randint(1, 10, (2, 3))

array([[6, 9, 2],
       [9, 3, 2]])

In [47]:
array = np.random.randint(1, 1000, 10)
array

array([372, 160, 147, 750, 394,  83, 162, 819,  17, 576])

In [49]:
array > 500

array([False, False, False,  True, False, False, False,  True, False,
        True])

In [50]:
array[array > 500]

array([750, 819, 576])

In [51]:
array[:4] = 0
array

array([  0,   0,   0,   0, 394,  83, 162, 819,  17, 576])

In [52]:
array[4:]

array([394,  83, 162, 819,  17, 576])