In [1]:
import tensorflow as tf

: 

In [2]:
tf.__version__

'2.19.0'

In [3]:
print(tf.__doc__)


Top-level module of TensorFlow. By convention, we refer to this module as
`tf` instead of `tensorflow`, following the common practice of importing
TensorFlow via the command `import tensorflow as tf`.

The primary function of this module is to import all of the public TensorFlow
interfaces into a single place. The interfaces themselves are located in
sub-modules, as described below.

Note that the file `__init__.py` in the TensorFlow source code tree is actually
only a placeholder to enable test cases to run. The TensorFlow build replaces
this file with a file generated from [`api_template.__init__.py`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/api_template.__init__.py)



# Tensor - date

# Crearea unor tensori constanti

In [5]:
# Scalar (tensorflow de rank 0)
scalar = tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
scalar.ndim

0

In [8]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
vector.ndim

1

In [10]:
matrix = tf.constant([[10, 7], [3, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5]], dtype=int32)>

In [11]:
matrix.ndim

2

Default datatype este float32 si int32

In [14]:
matrix = tf.constant([[10, 7], [3, 5.0]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  5.]], dtype=float32)>

In [16]:
matrix = tf.constant([[10, 7], [3, 5]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  5.]], dtype=float16)>

# Crearea unor tensori variabili

In [18]:
tensor_variabil = tf.Variable([10, 3])
tensor_constant = tf.constant([10, 3])

# In python nu exista conceptul de constant

In [19]:
x = 3.14

In [20]:
import math

In [21]:
y = math.pi

In [22]:
y

3.141592653589793

In [24]:
math.pi = 3.14

In [25]:
math.pi

3.14

In [26]:
tensor_variabil[0] = 888
tensor_variabil

TypeError: 'ResourceVariable' object does not support item assignment

In [28]:
tensor_variabil[0].assign(888)
tensor_variabil

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([888,   3], dtype=int32)>

# Nu functioneaza assign-ul

In [30]:
tensor_constant[0].assign(888)
tensor_constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Generare de tensori random

Seed -> intotdeauna imi generaza acelasi rezultat (folosind functia random)

In [36]:
random_gen1 = tf.random.Generator.from_seed(42)

In [ ]:
tf.random.Generator.from_seed(42)

In [37]:
random_gen1.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [38]:
random_gen2 = tf.random.Generator.from_seed(42)
random_gen2.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [39]:
random_gen1, random_gen2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7dd59b349eb0>,
 <tensorflow.python.ops.stateful_random_ops.Generator at 0x7dd59b5d65a0>)

In [40]:
random_gen1 == random_gen2

False

In [42]:
random_gen3 = tf.random.Generator.from_seed(101)
random_gen3.normal(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.08036723, -1.7199678 ],
       [-0.6891769 ,  0.22862972],
       [-0.69891334, -0.11101238]], dtype=float32)>

In [43]:
tf.random.shuffle(tensor_variabil)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([  3, 888], dtype=int32)>

In [44]:
tf.random.shuffle(tf.constant([[10, 7], [3, 5]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  5],
       [10,  7]], dtype=int32)>

## Alte forme de a crea tensori

In [45]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [46]:
tf.ones(shape=10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [47]:
tf.zeros(shape=8)

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

# Creare tensori cu ajutorul numpy

In [48]:
import numpy as np


In [50]:
numpy_vector = np.arange(1, 11, dtype=np.int32)
numpy_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [52]:
tensor_from_numpy = tf.constant(numpy_vector)
tensor_from_numpy

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)>

In [53]:
tensor_from_numpy.numpy()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

# Operatii cu tensori

In [54]:
tf.ones(10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [55]:
tf.ones(10) + 2

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.], dtype=float32)>

In [56]:
tf.ones(10) * 2.1

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1], dtype=float32)>

In [57]:
tensor1 = tf.constant([[1, 2],[1, 3]])
tensor2 = tf.constant([[1, 1], [1, 1]])


In [58]:
tensor1 + tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 4]], dtype=int32)>

In [59]:
tensor1 * tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 3]], dtype=int32)>

In [61]:
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [4, 4]], dtype=int32)>

In [62]:
tensor_r =  tf.ones(10)
tensor_r

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [64]:
tf.reshape(tensor_r, shape=(2,5))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [66]:
random_tensor = tf.constant(np.random.random(50))
random_tensor

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.59394941, 0.14130055, 0.24551298, 0.60940445, 0.7098549 ,
       0.94497814, 0.74035182, 0.80538751, 0.84147855, 0.12182085,
       0.62816727, 0.1272684 , 0.41206579, 0.84815198, 0.26676113,
       0.48315   , 0.1901496 , 0.20751686, 0.47383802, 0.70536305,
       0.99663826, 0.98016623, 0.10524317, 0.65775781, 0.92099965,
       0.82768152, 0.37665099, 0.33844056, 0.0422112 , 0.35986258,
       0.53556935, 0.90145497, 0.23316711, 0.94422256, 0.48287469,
       0.75963555, 0.0823776 , 0.41248476, 0.11494195, 0.82843649,
       0.57405507, 0.97735993, 0.68737835, 0.35505895, 0.37646592,
       0.45804659, 0.60988645, 0.99627289, 0.42274558, 0.48767958])>

In [68]:
tf.argmax(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [69]:
random_tensor[20]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9966382553495505>